project_id = "wjxskortepwwxdkpufzq"

[functions.redeem-code]
verify_jwt = false

[functions.credit-user]
verify_jwt = true

[functions.settle-match]
verify_jwt = true

[functions.aviator-controller]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
